name: Tests and Static Analysis

on:
  pull_request:
    branches:
    - main

jobs:
  # Label of the container job
  test:
    name: PHP ${{ matrix.php-versions }} + ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-20.04']
        php-versions: ['7.4', '8.0']
        phpunit-versions: ['9.5']
    # Service containers to run with `runner-job`

    steps:
      # Downloads a copy of the code in the repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, phpunit:9.5
          coverage: pcov

      - name: Install Composer Dependencies
        run: composer install

      - name: Run Tests
        run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

      - name: Send coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/clover.xml